LMS XML updates
AWGL/somatic_db pull request #100
Opened 2024-01-24 12:12 UTC by erikwaskiewicz

Fix issue #90 

- Added a `report_snv_vaf` field to the panels model, which will control whether VAF is exported to the LIMS XML or not
- Changed the XML template so that VAF is blank if `report_snv_vaf` is False
- Split the gap description into gene and HGVSc so they can be separate fields on the LIMS XML (transcript no longer included but that's fine)
- Tidied up the gaps display on the depth tab, it was different for different depth cutoffs
- Fixed test data so that the gap description is in the correct format, there was a bug in the pipeline where it was missing a colon which has since been fixed, the data must have been generated before the bug fix
- Only output genuine variants to the report tab, PDF and XML. 
- Add a sentence saying this to the report tab and PDF
- Add a list of failed/miscalled calls to the PDF so checkers can know if they might want to go back into the SVD to look into them

2024-01-24 13:09 UTC, Istaisa commented on analysis/templates/analysis/analysis-report.html
> +<small class="form-text text-muted">Only genuine variants are displayed here, see 'SNVs & indels' tab for all calls</small>
this line is showing up below the table in my pdf output for some reason

2024-01-24 13:11 UTC, Istaisa commented on analysis/templates/analysis/download_report.html
> +  <small class="form-text text-muted">Only genuine variants are displayed here, any miscalled or failed calls are listed at the end of this report</small>
Ah here's why it's displaying under! can we move this to be above the table?

2024-01-24 13:12 UTC, Istaisa commented on analysis/templates/analysis/analysis-report.html
> +<small class="form-text text-muted">Only genuine variants are displayed here, see 'SNVs & indels' tab for all calls</small>
because it's the other html. resolving my own point.

2024-01-24 13:17 UTC, Istaisa commented on analysis/templates/analysis/download_report.html
> +  <!-- list any miscalled or failed fusions -->
Could we maybe add a "no miscalled/failed variants" if there's nothing?

2024-01-24 13:27 UTC, Istaisa requested changes
Generally looks good and works as expected - a couple of minor changes.

Also the live database will need tidying up on deploy (already discussed) to clear up existing gaps in "old" format as samples with these will not load

2024-01-24 17:14 UTC, erikwaskiewicz commented on analysis/templates/analysis/download_report.html
> +  <small class="form-text text-muted">Only genuine variants are displayed here, any miscalled or failed calls are listed at the end of this report</small>
Fixed in [be94c15](https://github.com/AWGL/somatic_db/pull/100/commits/be94c15a5ef26915511e59c23676903d5c5aaed1)

2024-01-24 17:14 UTC, erikwaskiewicz commented on analysis/templates/analysis/download_report.html
> +  <!-- list any miscalled or failed fusions -->
Fixed in [ec57a40](https://github.com/AWGL/somatic_db/pull/100/commits/ec57a40d7f461cce683944c1e4ba4fc1327fe58b)

2024-01-24 17:14 UTC, erikwaskiewicz commented on analysis/templates/analysis/download_report.html
> +  {% if sample_data.panel_obj.show_fusions %}
Fixed in [ec57a40](https://github.com/AWGL/somatic_db/pull/100/commits/ec57a40d7f461cce683944c1e4ba4fc1327fe58b)

2024-01-24 17:16 UTC, erikwaskiewicz commented on analysis/models.py
> +    report_snv_vaf = models.BooleanField(default=False)
I can already edit it, is it not available in yours? You have to click into the individual panel, I haven't added to the all panels page because I'm just leaving the main options there, there's too many to include otherwise

2024-01-25 12:04 UTC, Istaisa approved these changes
Changes checked, work as intended. Good to merge. Closes #90

2024-01-25 12:04 UTC, merged