Initial SWGS models and upload
AWGL/somatic_db pull request #130
Opened 2024-08-07 15:47 UTC by Istaisa

This is very much a work in progress but it puts down the fundamentals and I want to try and avoid one giant one at once.

Included in this pull request:

- The basic setup/settings changes etc. for an SWGS app
- Most of the models and their associated admin pages
- A run and patient analysis web page - currently exclusively for dev work
- an import script which puts the test information, qc information and snvs in to the database

Test data and running the imports:
After making migrations:
`manage.py import_wgs --patient_json test_patient_info.json --qc_json test_overall_qc.json --germline_snv_json test_germline_snv.json --somatic_snv_json test_somatic_snv.json`

Example jsons are available here: https://github.com/AWGL/dragenswgs_post_processing/tree/vcf_to_json/tests/test_data/test_svd_files
from the cell lines data. These will get moved in to SVD once they're finalised I've got some clinvar and cancer hotspots tweaked to make.

2024-08-15 09:51 UTC, Istaisa commented
Added basic CSV download functionality - closes #131 . Currently it downloads everything displayed on webpage, I can add in clinvar, cancer hotspots etc. as well, I just need to update my SVD test dataset for those.
We can comment out the SWGS link from the main bar to put it live in the background.

2024-08-21 08:32 UTC, erikwaskiewicz requested changes
Looks really good, really easy to setup and test. I've added some comments inline, can you look at those before we merge please? 

Here's some more general comments for future versions:

- You're going to have to explain managers to me, code makes sense but they're not used. Might be a future thing
- future problem but we can probably share the main SVD home page rather than making a new one, if you're happy with that?
- breadcrumbs could have more detail so you can click back and forth easier but may change related to the above so something to sort when we're happy with the layout
- there's a lot of repetition between somatic and germline imports, could be simplified in future. Same with views but they're going to change a lot
- some logging on the import would be useful, I ran the same import script twice to see what happens and it only imported once, probably the right behaviour but would be good if theres a log to say so
- tests incomplete but pass so far

2024-08-21 08:32 UTC, erikwaskiewicz commented on analysis/templates/analysis/base.html
> +          <li class="nav-item px-2">
Do we want to hide this so the SWGS is more discrete until we go live?

2024-08-21 08:32 UTC, erikwaskiewicz commented on swgs/models.py
> +    An individual patient. Primary key is the NHS number.
Is comment out of date? Looks like its just an autonumber?

2024-08-21 08:32 UTC, erikwaskiewicz commented on swgs/models.py
> +    id = models.AutoField(primary_key=True)
Can id be in the abstract class? Its in every instance its used, might not be possible though

2024-08-21 08:32 UTC, erikwaskiewicz commented on swgs/models.py
> +    #TODO make a fixture
You've done this, todo can be removed?

2024-08-21 08:32 UTC, erikwaskiewicz commented on swgs/models.py
> +    id = models.AutoField(primary_key=True)
same question as the QC models - can the id be part of the abstract class, I assume its probably not possible but asking just in case :)

This is also quite fussy but can these go straight after the abstract class so I dont have to scroll up and down please?

2024-08-21 08:48 UTC, Istaisa commented on swgs/templates/swgs/view_patient_analysis.html
> +    <li>Variants are excluded if their most severe consequence is a MODIFIER strength - see <a href="https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html">VEP Documentation</a
Done. Did not know this thanks!

2024-08-21 08:50 UTC, Istaisa commented on analysis/templates/analysis/base.html
> +          <li class="nav-item px-2">
Yes we do. I've commented out for this pull request

2024-08-21 08:55 UTC, Istaisa commented on swgs/models.py
> +    An individual patient. Primary key is the NHS number.
yes it is. fixed.

2024-08-21 09:07 UTC, Istaisa commented on swgs/models.py
> +    id = models.AutoField(primary_key=True)
You can! This has gone through many iterations of primary keys being different things. I'm leaning towards everything being an id now though so will update everything accordingly.

2024-08-21 09:09 UTC, Istaisa commented on swgs/models.py
> +    id = models.AutoField(primary_key=True)
you're right those models were in the wrong order.

2024-08-21 09:15 UTC, Istaisa commented
All inline comments resolved.

- Managers - yeah we'll talk about these. They're going to get involved again when the fixtures get more complex but yes for now they're not used - they were in v1 of my test data but I've turned everything to jsons since. If we leave for now I'll update or delete as appropriate when SNVs are in a more useable state
- I was also thinking one main homepage
- Breadcrumbs: definitely open to any HTML suggestions that is not my strong suit. Maybe if we do a HTML/design sitdown further down the line
- Repetition - agree, i'll fix it when all the code's in place and I know what I'm refactoring
- Agree with the logging comments. I need to add clinvar and cancer hostpots as these have been updated in the pipeline since, I'll add logging comments when I do that
- There will be so many more tests

2024-08-21 09:36 UTC, erikwaskiewicz approved these changes
Happy with changes, I've also commented out the SVD button at the top as discussed

2024-08-21 09:38 UTC, merged