Xml
AWGL/somatic_db pull request #61
Opened 2023-07-17 16:30 UTC by erikwaskiewicz

## Change description
- Download an XML for LIMS from clicking dropdown now part of the download PDF button
- Add page numbers to PDF, uses different package so env has changed
- Fix issue #47 
- Fix bug where you couldnt reopen a sample fail or enter a fail 2nd check if you're assigned to it, also tidy up of that page because there's lots of different options

## Justification for minor update
No effect on processing of data, only how it's visualised

## Testing description
- Running existing unit tests
- LIMS XML not needed yet, will be tested as part of LIMS validation, may be tweaked as we go along
- Manual testing of database functionality
  - XML downloads and data matches report tab
  - tried all possible combinations for the assigned to buttons on the samples page, shown in the comments of `view_samples.html`
  - Tested that text after hash is successfully removed when going onto the `view_samples.html` page (analyse one run normally and when you're redirected back there should be no hash)

## Test data location
N/A

## Verification results
- Unit tests all completed successfully
- Database testing listed above all performed as expected
- Deployment:
  - No model changes so will be straightforward. 
  - Notify CS about PDF changes in case there's any weird formatting that needs fixing on the fly
  - Cant specify output location for PDF/XML due to security issues, but can show CS how to set up browser to save as rather than just download straight into download folder  
  - Conda environment will need updating, test with different env name first as Viglen conda is temperamental

2023-07-24 08:51 UTC, Istaisa commented
All unit tests pass.

2023-07-24 09:20 UTC, Istaisa commented
Manual testing: XML
- **No XML download for failed samples - is this intentional?**
- Compared XML download and data for 2 passed samples - data identical between database and XML

2023-07-24 09:48 UTC, Istaisa commented
Manual testing: PDF

- Pages number correctly
- "No calls" in variants table when no calls
- "No hotspot gaps" in gaps table when no gaps
- **For POLE gaps, all gaps show as POLE(NM_006231.3):c.NA_NA on web app and on download - this is also true of live SVD. Possibly because in the regions, formatting is e.g. POLE(NM006231.3):c.1376_p.(Ser459Phe) rather than POLE(NM006231.3):c.1376_1376_p.(Ser459Phe)**
- Data matches between download and web app - tested for 3 samples
- PDF output formatting is good

2023-07-24 10:47 UTC, Istaisa commented
Manual Testing: Poly Lists

- **The 'tag' next to the Build 38 poly list title reads GRCh37**
- **Pages don't load without existing polylist objects - could be helpful to add this to fixtures/readme for dev**
- Same user cannot check polys - good
- **Cannot add b38 variants to b38 polylist. Tried b38 with/without chr and b37 just in case. Will investigate in code.**

2023-07-24 11:18 UTC, Istaisa commented
fight-209 not included in the panels_march2023 json as a b37 TSO500 DNA referral (there for b37 RNA, b38 DNA and RNA) so one sample from 37 test data does not upload

2023-07-24 11:42 UTC, Istaisa requested changes
Summary of changes requested:

- XML download for failed samples (EW to discuss with clinical scientists)
- POLE gaps addressed in SS pipeline update
- Minor changes to code - mostly aesthetic and 1 variable name correction, see individual comments
- Minor changes to fixtures to ensure smooth dev - polylists in fixtures, update panels with fight-209 b37 dna and aml

Otherwise all looking good!

2023-07-24 11:42 UTC, Istaisa commented on analysis/management/commands/import.py
> +        if 'percent_cosmic' not in gaps.keys():
gap not gaps

2023-07-25 10:37 UTC, erikwaskiewicz commented on analysis/templates/analysis/options_page.html
> +        <h5 class="card-title">Build 38 poly list <span class="badge badge-success">GRCh37</span></h5>
Good spot, thanks. Fixed in latest commits

2023-07-25 10:38 UTC, erikwaskiewicz commented on env.yaml
> +- conda-forge::python-pdfkit=1.0.
Yes, fixed in recent commits

2023-07-25 10:38 UTC, erikwaskiewicz commented on analysis/management/commands/import.py
> +        if 'percent_cosmic' not in gaps.keys():
Good spot, fixed in latest commits

2023-07-25 10:38 UTC, erikwaskiewicz commented
> XML download for failed samples (EW to discuss with clinical scientists)

- Thanks for spotting this, will discuss with CS. XML may go through a few iterations before final version is done

> POLE gaps addressed in SS pipeline update

- Yes, this is an issue with the bed2hgvs part for the current pipeline, it cant annotate POLE (and a few other genes) so just defaults to NA. New pipeline will resolve this issue

> Minor changes to code - mostly aesthetic and 1 variable name correction, see individual comments

- Done, replied to individual comments

> Minor changes to fixtures to ensure smooth dev - polylists in fixtures, update panels with fight-209 b37 dna and aml

- Polylist fixture added, it will just add the objects but no actual polys
- I've edited the poly list script and put instructions on how to fill from the poly list text files if polys are needed in the database, also includes a flag to prevent us having to double check them all for dev work
- The readme has been updated with this info and made deploy instructions clearer
- I havent updated the panels yet as I want to do a cleanup on deploy and do it all in one go, there's a few more panels in main on Viglen that aren't in here too

2023-07-25 11:02 UTC, Istaisa approved these changes
Tried new poly list upload - works great.
Unit tests still pass.
Merging with outstanding XML issue as this has been raised and will be developed in further releases.

2023-07-25 11:02 UTC, merged