Home page
AWGL/somatic_db pull request #86
Opened 2023-12-04 13:28 UTC by erikwaskiewicz

## Change description
- Add a home page

## Justification for minor update
No effect on processing of data, only how it's visualised

## Testing description
- Running existing unit tests
- 

## Test data location
N/A

## Verification results
-

2023-12-15 10:51 UTC, Istaisa commented on analysis/templates/analysis/home.html
> +        <p><a class="btn btn-info w-100" href="{% url 'view_worksheets' 'training' %}">All training/ validation worksheets</a></p>
This is me being petty but, there's inconsistent use of Thing1/ Thing2 and Thing1/Thing2 throughout this page could they all be the same

2023-12-15 10:52 UTC, Istaisa commented on analysis/templates/analysis/home.html
> +          <li>Any samples currently assined to you will appear in 1st box to the left, box will be yellow/green depending if you do/dont have anything assigned to you</li>
Typo assined --> assigned, dont --> don't

2023-12-15 10:54 UTC, Istaisa commented on analysis/templates/analysis/home.html
> +          <li>View any worksheet that has samples that arent completed in 2nd box to the left, again colur coded as above</li>
Typo colur --> colour, arent --> aren't

2023-12-15 12:05 UTC, Istaisa commented on analysis/views.py
> +        # TODO this will load in all worksheets first, is there a quicker way?
We could do the checks/worksheets in a single query but it would be hideous and possibly slower than doing all the worksheets plus list comprehension. I'll have a think though.

2023-12-15 13:40 UTC, Istaisa requested changes
Homepage looks great!

Unit tests all pass. 

Checked logic of the code and all seems good. Search bar works as expected, user and worksheet queries worked as expected.

Minor typos to fix.

Also might be good to have a big obvious polylist button in quick links?

2023-12-15 16:41 UTC, Istaisa commented
Note: Code reviewed Sophie's changes and merged

2023-12-18 17:55 UTC, erikwaskiewicz commented on analysis/templates/analysis/home.html
> +        <p><a class="btn btn-info w-100" href="{% url 'view_worksheets' 'training' %}">All training/ validation worksheets</a></p>
Fixed in latest commits

2023-12-18 17:55 UTC, erikwaskiewicz commented on analysis/templates/analysis/home.html
> +          <li>Any samples currently assined to you will appear in 1st box to the left, box will be yellow/green depending if you do/dont have anything assigned to you</li>
Fixed in latest commits

2023-12-18 17:55 UTC, erikwaskiewicz commented on analysis/templates/analysis/home.html
> +          <li>View any worksheet that has samples that arent completed in 2nd box to the left, again colur coded as above</li>
Fixed in latest commits

2023-12-18 17:57 UTC, erikwaskiewicz commented on analysis/views.py
> +        # TODO this will load in all worksheets first, is there a quicker way?
I think I'll leave it in for now, will see how the other improvements affect the speed of the database and then come back to it

2023-12-18 17:57 UTC, erikwaskiewicz commented
Fixed all issues, can you check that they're all okay please @Istaisa

2023-12-19 08:47 UTC, Istaisa approved these changes
Changes look good, okay to merge.

2023-12-19 08:48 UTC, merged